version: '3.8'

services:
  app:
    container_name: my_app
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - my_mongo
      - my_redis
    volumes:
          - ./logs:/app/logs
    env_file:
      - ./.env
  my_mongo:
    container_name: my_mongo
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PWD}
    ports:
      - "27017:27017"
  my_redis:
    container_name: my_redis
    image: redis:latest
#    command: redis-server --requirepass 'admin'
    environment:
#      - MONGO_INITDB_ROOT_PASSWORD=${REDIS_PWD}
    volumes:
#      - ./mongodb_data:/var/lib/mongo/data
    ports:
      - "6379:6379"